services:
  - type: web
    name: n8n-server-final
    runtime: node
    plan: free
    region: singapore
    buildCommand: "npm install --production"
    startCommand: "npm start"
    envVars:
      - key: N8N_PORT
        value: 10000
      - key: N8N_ENCRYPTION_KEY
        value: "tneSIPQK3+GB3gVuRAsbb5t4Mhu/LgQi"
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: "ENTER_YOUR_NEON_DB_NAME"
      - key: DB_POSTGRESDB_HOST
        value: "ENTER_YOUR_NEON_HOST"
      - key: DB_POSTGRESDB_USER
        value: "ENTER_YOUR_NEON_USER"
      - key: DB_POSTGRESDB_PASSWORD
        value: "ENTER_YOUR_NEON_PASSWORD"
