services:
  - type: web
    name: n8n-cloud-server
    runtime: node
    plan: free
    region: singapore
    buildCommand: "npm install --production"
    startCommand: "npm start"
    envVars:
      - key: N8N_PORT
        value: 10000
      - key: N8N_ENCRYPTION_KEY
        value: "tneSIPQK3+GB3gVuRAsbb5t4Mhu/LgQi"
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: "ENTER_NEON_DB_NAME_HERE"
      - key: DB_POSTGRESDB_HOST
        value: "ENTER_NEON_HOST_HERE"
      - key: DB_POSTGRESDB_USER
        value: "ENTER_NEON_USER_HERE"
      - key: DB_POSTGRESDB_PASSWORD
        value: "ENTER_NEON_PASSWORD_HERE"
