services:
  - type: web
    name: n8n-cloud-server
    runtime: node
    plan: free
    region: singapore
    buildCommand: "npm install --production"
    startCommand: "npm start"
    envVars:
      - key: N8N_PORT
        value: 10000
      - key: N8N_ENCRYPTION_KEY
        value: "tneSIPQK3+GB3gVuRAsbb5t4Mhu/LgQi"
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: "neondb"
      - key: DB_POSTGRESDB_HOST
        value: "ep-broad-wind-aiyqb50t-pooler.c-4.us-east-1.aws.neon.tech"
      - key: DB_POSTGRESDB_USER
        value: "neondb_owner"
      - key: DB_POSTGRESDB_PASSWORD
        value: "npg_akCs1DZblHL7"
